export interface ChangelogEntry {
  version: string;
  date: string;
  features: string[];
  bugfixes?: string[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "1.7.0",
    date: "2026-05-31",
    features: [
      "One Language at a Time: training sessions are now locked to a single language to prevent interference between languages",
      "Language picker screen shown at the start of every training session — choose the language for today",
      "Active session language lock banner displayed during training with an 'End Session' button",
      "AI vocabulary generation (training page and vocabulary page) now scopes to the active session language only",
      "Session language resets on page refresh, enforcing the one-language-per-session rule",
      "Session complete screen includes a 'New Language Session' button to switch to another language",
      "Vocabulary page 'AI Suggest' button shows lock icon and language name when a session is active",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-05-31",
    features: [
      "Audit panel: check open-source license compliance and prevent 1:1 copying of commercial features",
      "Proficiency-aware AI suggestions: vocabulary difficulty adapts to user level",
      "Duplicate prevention: AI no longer generates vocabulary that already exists for the same language",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-05-31",
    features: [
      "AI-generated images for all vocabulary words including verbs",
      "Images are automatically generated whenever new vocabulary is added via AI",
      "Existing vocabulary entries are updated with images on demand",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-05-30",
    features: [
      "Star/favorites system on flashcards to bookmark vocabulary",
      "Vocabulary editing: update word, translation, and category inline",
      "AI word suggestions: let AI propose new vocabulary for a selected category",
    ],
    bugfixes: [
      "Fixed SM-2 spaced repetition algorithm scheduling edge cases",
      "Corrected interval calculation for newly mastered words",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-05-30",
    features: [
      "Settings page: configure native language, target language, and proficiency level",
      "Daily goal setting and exercise type preferences",
      "Changelog sidebar entry (this page)",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-05-30",
    features: [
      "High-quality neural text-to-speech with a pleasant female voice",
      "TTS support for example sentences in addition to individual words",
      "Switched to Mistral-only AI backend for faster and more consistent responses",
    ],
    bugfixes: [
      "Improved TTS audio quality to match Quizlet/Google Translate standards",
    ],
  },
  {
    version: "1.1.1",
    date: "2026-05-30",
    features: [
      "All UI content translated to English",
      "MIT License added with attribution to Damian Berghof",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-05-30",
    features: [
      "Mistral AI integration via private API key in .env",
      "ANKI-style spaced repetition (SM-2 algorithm): well-learned words repeat after increasing intervals",
      "Vocabulary organized by language and grammar category (nouns, verbs, adjectives, food, clothing, etc.)",
      "Context-sensitive example sentences generated by AI",
    ],
    bugfixes: [
      "Fixed vocabulary fetch failing on empty database",
      "Resolved routing issues in Next.js app router",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-05-30",
    features: [
      "Initial release of Polyglot AI Vocabulary Trainer",
      "Dashboard with progress stats and daily streak",
      "Flashcard, multiple-choice, and write exercises",
      "FastAPI backend with SQLite database",
      "Next.js 15 frontend with Tailwind CSS",
      "Docker Compose setup for easy deployment",
    ],
  },
];
